//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IvivuCustomer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DatPhong
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DatPhong()
        {
            this.HoaDons = new HashSet<HoaDon>();
        }
    
        public int maDP { get; set; }
        public short maLoaiPhong { get; set; }
        public short maPhong { get; set; }
        public int maKH { get; set; }
        public System.DateTime ngayBatDau { get; set; }
        public System.DateTime ngayTraPhong { get; set; }
        public System.DateTime ngayDat { get; set; }
        public int donGia { get; set; }
        public string moTa { get; set; }
        public string tinhTrang { get; set; }
    
        public virtual KhachHang KhachHang { get; set; }
        public virtual LoaiPhong LoaiPhong { get; set; }
        public virtual Phong Phong { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoaDon> HoaDons { get; set; }
    }
}
