//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IvivuCustomer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhanVien
    {
        public int maNV { get; set; }
        public string hoTen { get; set; }
        public string tenDangNhap { get; set; }
        public string matKhau { get; set; }
        public byte maKS { get; set; }
    
        public virtual KhachSan KhachSan { get; set; }
    }
}
