//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ivivu.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrangThaiPhong
    {
        public short maPhong { get; set; }
        public System.DateTime ngay { get; set; }
        public string tinhTrang { get; set; }
    
        public virtual Phong Phong { get; set; }
    }
}
